# Copyright (C) 2016 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/ulefone/U008_Pro/setup-makefiles.sh

#xbin
PRODUCT_COPY_FILES += \
    vendor/ulefone/U008_Pro/proprietary/xbin/mnld:system/xbin/mnld \
    vendor/ulefone/U008_Pro/proprietary/xbin/BGW:system/xbin/BGW

#bin
PRODUCT_COPY_FILES += \
    vendor/ulefone/U008_Pro/proprietary/bin/6620_launcher:system/bin/6620_launcher \
    vendor/ulefone/U008_Pro/proprietary/bin/6620_wmt_concurrency:system/bin/6620_wmt_concurrency \
    vendor/ulefone/U008_Pro/proprietary/bin/6620_wmt_lpbk:system/bin/6620_wmt_lpbk \
    vendor/ulefone/U008_Pro/proprietary/bin/AcdApiDaemon:system/bin/AcdApiDaemon \
    vendor/ulefone/U008_Pro/proprietary/bin/aee:system/bin/aee \
    vendor/ulefone/U008_Pro/proprietary/bin/aee_archive:system/bin/aee_archive \
    vendor/ulefone/U008_Pro/proprietary/bin/aee_core_forwarder:system/bin/aee_core_forwarder \
    vendor/ulefone/U008_Pro/proprietary/bin/aee_dumpstate:system/bin/aee_dumpstate \
    vendor/ulefone/U008_Pro/proprietary/bin/akmd09911:system/bin/akmd09911 \
    vendor/ulefone/U008_Pro/proprietary/bin/akmd8963:system/bin/akmd8963 \
    vendor/ulefone/U008_Pro/proprietary/bin/akmd8975:system/bin/akmd8975 \
    vendor/ulefone/U008_Pro/proprietary/bin/ami304d:system/bin/ami304d \
    vendor/ulefone/U008_Pro/proprietary/bin/bmm050d:system/bin/bmm050d \
    vendor/ulefone/U008_Pro/proprietary/bin/boot_logo_updater:system/bin/boot_logo_updater \
    vendor/ulefone/U008_Pro/proprietary/bin/ccci_fsd:system/bin/ccci_fsd \
    vendor/ulefone/U008_Pro/proprietary/bin/ccci_mdinit:system/bin/ccci_mdinit \
    vendor/ulefone/U008_Pro/proprietary/bin/dm_agent_binder:system/bin/dm_agent_binder \
    vendor/ulefone/U008_Pro/proprietary/bin/em_svr:system/bin/em_svr \
    vendor/ulefone/U008_Pro/proprietary/bin/fsck_msdos_mtk:system/bin/fsck_msdos_mtk \
    vendor/ulefone/U008_Pro/proprietary/bin/geomagneticd:system/bin/geomagneticd \
    vendor/ulefone/U008_Pro/proprietary/bin/gsm0710muxd:system/bin/gsm0710muxd \
    vendor/ulefone/U008_Pro/proprietary/bin/gsm0710muxdmd2:system/bin/gsm0710muxdmd2 \
    vendor/ulefone/U008_Pro/proprietary/bin/guiext-server:system/bin/guiext-server \
    vendor/ulefone/U008_Pro/proprietary/bin/kpoc_charger:system/bin/kpoc_charger \
    vendor/ulefone/U008_Pro/proprietary/bin/lcdc_screen_cap:system/bin/lcdc_screen_cap \
    vendor/ulefone/U008_Pro/proprietary/bin/lsm303md:system/bin/lsm303md \
    vendor/ulefone/U008_Pro/proprietary/bin/mc6420d:system/bin/mc6420d \
    vendor/ulefone/U008_Pro/proprietary/bin/md_ctrl:system/bin/md_ctrl \
    vendor/ulefone/U008_Pro/proprietary/bin/mdlogger:system/bin/mdlogger \
    vendor/ulefone/U008_Pro/proprietary/bin/memsicd:system/bin/memsicd \
    vendor/ulefone/U008_Pro/proprietary/bin/memsicd3416x:system/bin/memsicd3416x \
    vendor/ulefone/U008_Pro/proprietary/bin/mobile_log_d:system/bin/mobile_log_d \
    vendor/ulefone/U008_Pro/proprietary/bin/msensord:system/bin/msensord \
    vendor/ulefone/U008_Pro/proprietary/bin/mtk_agpsd:system/bin/mtk_agpsd \
    vendor/ulefone/U008_Pro/proprietary/bin/MtkCodecService:system/bin/MtkCodecService \
    vendor/ulefone/U008_Pro/proprietary/bin/mtkrild:system/bin/mtkrild \
    vendor/ulefone/U008_Pro/proprietary/bin/mtkrildmd2:system/bin/mtkrildmd2 \
    vendor/ulefone/U008_Pro/proprietary/bin/muxreport:system/bin/muxreport \
    vendor/ulefone/U008_Pro/proprietary/bin/netdiag:system/bin/netdiag \
    vendor/ulefone/U008_Pro/proprietary/bin/nvram_agent_binder:system/bin/nvram_agent_binder \
    vendor/ulefone/U008_Pro/proprietary/bin/nvram_daemon:system/bin/nvram_daemon \
    vendor/ulefone/U008_Pro/proprietary/bin/orientationd:system/bin/orientationd \
    vendor/ulefone/U008_Pro/proprietary/bin/ppl_agent:system/bin/ppl_agent \
    vendor/ulefone/U008_Pro/proprietary/bin/pppd:system/bin/pppd \
    vendor/ulefone/U008_Pro/proprietary/bin/pppd_dt:system/bin/pppd_dt \
    vendor/ulefone/U008_Pro/proprietary/bin/pq:system/bin/pq \
    vendor/ulefone/U008_Pro/proprietary/bin/program_binary_service:system/bin/program_binary_service \
    vendor/ulefone/U008_Pro/proprietary/bin/qmcX983d:system/bin/qmcX983d \
    vendor/ulefone/U008_Pro/proprietary/bin/s62xd:system/bin/s62xd \
    vendor/ulefone/U008_Pro/proprietary/bin/sn:system/bin/sn \
    vendor/ulefone/U008_Pro/proprietary/bin/terservice:system/bin/terservice \
    vendor/ulefone/U008_Pro/proprietary/bin/thermal:system/bin/thermal \
    vendor/ulefone/U008_Pro/proprietary/bin/thermald:system/bin/thermald \
    vendor/ulefone/U008_Pro/proprietary/bin/thermal_manager:system/bin/thermal_manager \
    vendor/ulefone/U008_Pro/proprietary/bin/uiautomator:system/bin/uiautomator \
    vendor/ulefone/U008_Pro/proprietary/bin/wifi2agps:system/bin/wifi2agps \
    vendor/ulefone/U008_Pro/proprietary/bin/wmt_loader:system/bin/wmt_loader \
    vendor/ulefone/U008_Pro/proprietary/bin/xlog:system/bin/xlog \
    vendor/ulefone/U008_Pro/proprietary/bin/batterywarning:system/bin/batterywarning \
    vendor/ulefone/U008_Pro/proprietary/bin/emdlogger1:system/bin/emdlogger1 \
    vendor/ulefone/U008_Pro/proprietary/bin/fuelgauged:system/bin/fuelgauged \
    vendor/ulefone/U008_Pro/proprietary/bin/gas_srv:system/bin/gas_srv \
    vendor/ulefone/U008_Pro/proprietary/bin/ged_srv:system/bin/ged_srv \
    vendor/ulefone/U008_Pro/proprietary/bin/magd:system/bin/magd \
    vendor/ulefone/U008_Pro/proprietary/bin/matv:system/bin/matv \
    vendor/ulefone/U008_Pro/proprietary/bin/radvd:system/bin/radvd \
    vendor/ulefone/U008_Pro/proprietary/bin/spm_loader:system/bin/spm_loader \
    vendor/ulefone/U008_Pro/proprietary/bin/stp_dump3:system/bin/stp_dump3
    
    

#lib
PRODUCT_COPY_FILES += \
    vendor/ulefone/U008_Pro/proprietary/lib/lib3a.so:system/lib/lib3a.so \
    vendor/ulefone/U008_Pro/proprietary/lib/liba3m.so:system/lib/liba3m.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libacdk.so:system/lib/libacdk.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libaed.so:system/lib/libaed.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libaudiocompensationfilter.so:system/lib/libaudiocompensationfilter.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libaudiocomponentengine.so:system/lib/libaudiocomponentengine.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libaudiocustparam.so:system/lib/libaudiocustparam.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libaudiodcrflt.so:system/lib/libaudiodcrflt.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libaudiomtkdcremoval.so:system/lib/libaudiomtkdcremoval.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libaudio-resampler.so:system/lib/libaudio-resampler.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libaudiosetting.so:system/lib/libaudiosetting.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libbessound_hd_mtk.so:system/lib/libbessound_hd_mtk.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libbessurround_mtk.so:system/lib/libbessurround_mtk.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libblisrc32.so:system/lib/libblisrc32.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libblisrc.so:system/lib/libblisrc.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libbluetoothem_mtk.so:system/lib/libbluetoothem_mtk.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libbluetooth_mtk_pure.so:system/lib/libbluetooth_mtk_pure.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libbluetooth_mtk.so:system/lib/libbluetooth_mtk.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libbluetooth_relayer.so:system/lib/libbluetooth_relayer.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libBnMtkCodec.so:system/lib/libBnMtkCodec.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libbt-vendor.so:system/lib/libbt-vendor.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libbwc.so:system/lib/libbwc.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libcam1_utils.so:system/lib/libcam1_utils.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libcam3_app.so:system/lib/libcam3_app.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libcam3_hwnode.so:system/lib/libcam3_hwnode.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libcam3_hwpipeline.so:system/lib/libcam3_hwpipeline.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libcam3_pipeline.so:system/lib/libcam3_pipeline.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libcam3_utils.so:system/lib/libcam3_utils.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libcamalgo.so:system/lib/libcamalgo.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libcam.camadapter.so:system/lib/libcam.camadapter.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libcam.campipe.so:system/lib/libcam.campipe.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libcam.camshot.so:system/lib/libcam.camshot.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libcam.client.so:system/lib/libcam.client.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libcam.device1.so:system/lib/libcam.device1.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libcam.device3.so:system/lib/libcam.device3.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libcamdrv_FrmB.so:system/lib/libcamdrv_FrmB.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libcamdrv.so:system/lib/libcamdrv.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libcameracustom.so:system/lib/libcameracustom.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libcam.exif.so:system/lib/libcam.exif.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libcam.exif.v3.so:system/lib/libcam.exif.v3.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libcam.hal3a.v3.dng.so:system/lib/libcam.hal3a.v3.dng.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libcam.hal3a.v3.so:system/lib/libcam.hal3a.v3.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libcam.halsensor.so:system/lib/libcam.halsensor.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libcam_hwutils.so:system/lib/libcam_hwutils.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libcam.iopipe_FrmB.so:system/lib/libcam.iopipe_FrmB.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libcam.iopipe.so:system/lib/libcam.iopipe.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libcam.metadataprovider.so:system/lib/libcam.metadataprovider.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libcam.metadata.so:system/lib/libcam.metadata.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libcam_mmp.so:system/lib/libcam_mmp.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libcam.paramsmgr.so:system/lib/libcam.paramsmgr.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libcam_platform.so:system/lib/libcam_platform.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libcam.sdkclient.so:system/lib/libcam.sdkclient.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libcam.utils.sensorlistener.so:system/lib/libcam.utils.sensorlistener.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libcam_utils.so:system/lib/libcam_utils.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libcam.utils.so:system/lib/libcam.utils.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libccci_util.so:system/lib/libccci_util.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libClearMotionFW.so:system/lib/libClearMotionFW.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libcurl.so:system/lib/libcurl.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libcustom_nvram.so:system/lib/libcustom_nvram.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libcustom_prop.so:system/lib/libcustom_prop.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libcvsd_mtk.so:system/lib/libcvsd_mtk.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libdpframework.so:system/lib/libdpframework.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libdrmmtkutil.so:system/lib/libdrmmtkutil.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libdrmmtkwhitelist.so:system/lib/libdrmmtkwhitelist.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libem_bt_jni.so:system/lib/libem_bt_jni.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libem_gpio_jni.so:system/lib/libem_gpio_jni.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libem_lte_jni.so:system/lib/libem_lte_jni.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libem_modem_jni.so:system/lib/libem_modem_jni.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libem_sensor_jni.so:system/lib/libem_sensor_jni.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libem_support_jni.so:system/lib/libem_support_jni.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libem_usb_jni.so:system/lib/libem_usb_jni.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libem_wifi_jni.so:system/lib/libem_wifi_jni.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libfeatureiodrv.so:system/lib/libfeatureiodrv.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libfeatureio.so:system/lib/libfeatureio.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libfile_op.so:system/lib/libfile_op.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libfmcust.so:system/lib/libfmcust.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libfprint-x32.so:system/lib/libfprint-x32.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libfs_mgr.so:system/lib/libfs_mgr.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libgas.so:system/lib/libgas.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libged.so:system/lib/libged.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libgpu_aux.so:system/lib/libgpu_aux.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libgralloc_extra.so:system/lib/libgralloc_extra.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libgui_ext.so:system/lib/libgui_ext.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libgybeauty420.so:system/lib/libgybeauty420.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libgybeauty422.so:system/lib/libgybeauty422.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libgybeauty.so:system/lib/libgybeauty.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libh264enc_sa.ca7.so:system/lib/libh264enc_sa.ca7.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libh264enc_sb.ca7.so:system/lib/libh264enc_sb.ca7.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libhdrproc.so:system/lib/libhdrproc.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libHEVCdec_sa.ca7.android.so:system/lib/libHEVCdec_sa.ca7.android.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libhevce_sb.ca7.android.so:system/lib/libhevce_sb.ca7.android.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libhwm.so:system/lib/libhwm.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libimageio_FrmB.so:system/lib/libimageio_FrmB.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libimageio_plat_drv_FrmB.so:system/lib/libimageio_plat_drv_FrmB.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libimageio_plat_drv.so:system/lib/libimageio_plat_drv.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libimageio.so:system/lib/libimageio.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libion_mtk.so:system/lib/libion_mtk.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libion.so:system/lib/libion.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libJpgDecPipe.so:system/lib/libJpgDecPipe.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libJpgEncPipe.so:system/lib/libJpgEncPipe.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libm4u.so:system/lib/libm4u.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libmal.so:system/lib/libmal.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libmatv_cust.so:system/lib/libmatv_cust.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libmdfx.so:system/lib/libmdfx.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libmhalImageCodec.so:system/lib/libmhalImageCodec.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libmmprofile.so:system/lib/libmmprofile.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libmmsdkservice.feature.so:system/lib/libmmsdkservice.feature.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libmmsdkservice.so:system/lib/libmmsdkservice.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libmnl.so:system/lib/libmnl.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libmp4enc_sa.ca7.so:system/lib/libmp4enc_sa.ca7.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libmp4enc_xa.ca7.so:system/lib/libmp4enc_xa.ca7.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libmsbc_mtk.so:system/lib/libmsbc_mtk.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libmtcloader.so:system/lib/libmtcloader.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libmtkcamera_client.so:system/lib/libmtkcamera_client.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libmtkcam_fwkutils.so:system/lib/libmtkcam_fwkutils.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libmtk_drvb.so:system/lib/libmtk_drvb.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libmtkjpeg.so:system/lib/libmtkjpeg.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libmtklimiter.so:system/lib/libmtklimiter.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libmtk_mmutils.so:system/lib/libmtk_mmutils.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libMtkOmxAdpcmDec.so:system/lib/libMtkOmxAdpcmDec.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libMtkOmxAdpcmEnc.so:system/lib/libMtkOmxAdpcmEnc.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libMtkOmxAlacDec.so:system/lib/libMtkOmxAlacDec.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libMtkOmxApeDec.so:system/lib/libMtkOmxApeDec.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libMtkOmxCore.so:system/lib/libMtkOmxCore.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libMtkOmxFlacDec.so:system/lib/libMtkOmxFlacDec.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libMtkOmxG711Dec.so:system/lib/libMtkOmxG711Dec.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libMtkOmxGsmDec.so:system/lib/libMtkOmxGsmDec.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libMtkOmxMp3Dec.so:system/lib/libMtkOmxMp3Dec.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libMtkOmxRawDec.so:system/lib/libMtkOmxRawDec.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libMtkOmxVdecEx.so:system/lib/libMtkOmxVdecEx.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libMtkOmxVenc.so:system/lib/libMtkOmxVenc.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libMtkOmxVorbisEnc.so:system/lib/libMtkOmxVorbisEnc.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libmtkshifter.so:system/lib/libmtkshifter.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libnvramagentclient.so:system/lib/libnvramagentclient.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libnvram_daemon_callback.so:system/lib/libnvram_daemon_callback.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libnvram_platform.so:system/lib/libnvram_platform.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libnvram_sec.so:system/lib/libnvram_sec.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libnvram.so:system/lib/libnvram.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libperfservicenative.so:system/lib/libperfservicenative.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libperfservice.so:system/lib/libperfservice.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libpq_cust.so:system/lib/libpq_cust.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libpq_prot.so:system/lib/libpq_prot.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libpqservice.so:system/lib/libpqservice.so \
    vendor/ulefone/U008_Pro/proprietary/lib/librilmtkmd2.so:system/lib/librilmtkmd2.so \
    vendor/ulefone/U008_Pro/proprietary/lib/librilmtk.so:system/lib/librilmtk.so \
    vendor/ulefone/U008_Pro/proprietary/lib/librrc.so:system/lib/librrc.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libsec_mem.so:system/lib/libsec_mem.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libshowlogo.so:system/lib/libshowlogo.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libspeech_enh_lib.so:system/lib/libspeech_enh_lib.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libstagefrighthw.so:system/lib/libstagefrighthw.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libSwJpgCodec.so:system/lib/libSwJpgCodec.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libtinyalsa.so:system/lib/libtinyalsa.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libtinycompress.so:system/lib/libtinycompress.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libtinyxml.so:system/lib/libtinyxml.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libui_ext.so:system/lib/libui_ext.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libuvtswenc_sa.ca7.android.so:system/lib/libuvtswenc_sa.ca7.android.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libvc1dec_sa.ca7.so:system/lib/libvc1dec_sa.ca7.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libvcodec_cap.so:system/lib/libvcodec_cap.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libvcodecdrv.so:system/lib/libvcodecdrv.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libvcodec_oal.so:system/lib/libvcodec_oal.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libvcodec_utility.so:system/lib/libvcodec_utility.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libvp8dec_sa.ca7.so:system/lib/libvp8dec_sa.ca7.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libvp8enc_sa.ca7.so:system/lib/libvp8enc_sa.ca7.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libvp9dec_sa.ca7.so:system/lib/libvp9dec_sa.ca7.so \
    vendor/ulefone/U008_Pro/proprietary/lib/libwebrtc_audio_preprocessing.so:system/lib/libwebrtc_audio_preprocessing.so \
    vendor/ulefone/U008_Pro/proprietary/lib/mtk-rilmd2.so:system/lib/mtk-rilmd2.so \
    vendor/ulefone/U008_Pro/proprietary/lib/mtk-ril.so:system/lib/mtk-ril.so

#lib/soundfx : 
#PRODUCT_COPY_FILES += \
#    vendor/ulefone/U008_Pro/proprietary/lib/soundfx/libaudiopreprocessing.so:system/lib/soundfx/libaudiopreprocessing.so \
#    vendor/ulefone/U008_Pro/proprietary/lib/soundfx/libbundlewrapper.so:system/lib/soundfx/libbundlewrapper.so \
#    vendor/ulefone/U008_Pro/proprietary/lib/soundfx/libdownmix.so:system/lib/soundfx/libdownmix.so \
#    vendor/ulefone/U008_Pro/proprietary/lib/soundfx/libeffectproxy.so:system/lib/soundfx/libeffectproxy.so \
#    vendor/ulefone/U008_Pro/proprietary/lib/soundfx/libldnhncr.so:system/lib/soundfx/libldnhncr.so \
#    vendor/ulefone/U008_Pro/proprietary/lib/soundfx/libreverbwrapper.so:system/lib/soundfx/libreverbwrapper.so \
#    vendor/ulefone/U008_Pro/proprietary/lib/soundfx/libvisualizer.so:system/lib/soundfx/libvisualizer.so

#lib/drm
PRODUCT_COPY_FILES += \
    vendor/ulefone/U008_Pro/proprietary/lib/drm/libdrmctaplugin.so:system/lib/drm/libdrmctaplugin.so \
    vendor/ulefone/U008_Pro/proprietary/lib/drm/libdrmmtkplugin.so:system/lib/drm/libdrmmtkplugin.so

#lib/egl
PRODUCT_COPY_FILES += \
    vendor/ulefone/U008_Pro/proprietary/lib/egl/libGLES_mali.so:system/lib/egl/libGLES_mali.so

#lib/hw
PRODUCT_COPY_FILES += \
    vendor/ulefone/U008_Pro/proprietary/lib/hw/audio.a2dp.default.so:system/lib/hw/audio.a2dp.default.so \
    vendor/ulefone/U008_Pro/proprietary/lib/hw/audio_policy.default.so:system/lib/hw/audio_policy.default.so \
    vendor/ulefone/U008_Pro/proprietary/lib/hw/audio_policy.stub.so:system/lib/hw/audio_policy.stub.so \
    vendor/ulefone/U008_Pro/proprietary/lib/hw/audio.primary.default.so:system/lib/hw/audio.primary.default.so \
    vendor/ulefone/U008_Pro/proprietary/lib/hw/audio.primary.mt6737m.so:system/lib/hw/audio.primary.mt6737m.so \
    vendor/ulefone/U008_Pro/proprietary/lib/hw/audio.r_submix.default.so:system/lib/hw/audio.r_submix.default.so \
    vendor/ulefone/U008_Pro/proprietary/lib/hw/audio.usb.default.so:system/lib/hw/audio.usb.default.so \
    vendor/ulefone/U008_Pro/proprietary/lib/hw/camera.mt6737m.so:system/lib/hw/camera.mt6737m.so \
    vendor/ulefone/U008_Pro/proprietary/lib/hw/gps.mt6737m.so:system/lib/hw/gps.mt6737m.so \
    vendor/ulefone/U008_Pro/proprietary/lib/hw/gralloc.default.so:system/lib/hw/gralloc.default.so \
    vendor/ulefone/U008_Pro/proprietary/lib/hw/gralloc.mt6737m.so:system/lib/hw/gralloc.mt6737m.so \
    vendor/ulefone/U008_Pro/proprietary/lib/hw/hwcomposer.mt6737m.so:system/lib/hw/hwcomposer.mt6737m.so \
    vendor/ulefone/U008_Pro/proprietary/lib/hw/keystore.default.so:system/lib/hw/keystore.default.so \
    vendor/ulefone/U008_Pro/proprietary/lib/hw/lights.mt6737m.so:system/lib/hw/lights.mt6737m.so \
    vendor/ulefone/U008_Pro/proprietary/lib/hw/local_time.default.so:system/lib/hw/local_time.default.so \
    vendor/ulefone/U008_Pro/proprietary/lib/hw/memtrack.mt6737m.so:system/lib/hw/memtrack.mt6737m.so \
    vendor/ulefone/U008_Pro/proprietary/lib/hw/power.default.so:system/lib/hw/power.default.so \
    vendor/ulefone/U008_Pro/proprietary/lib/hw/radio.fm.mt6737m.so:system/lib/hw/radio.fm.mt6737m.so \
    vendor/ulefone/U008_Pro/proprietary/lib/hw/sensors.mt6737m.so:system/lib/hw/sensors.mt6737m.so \
    vendor/ulefone/U008_Pro/proprietary/lib/hw/vibrator.default.so:system/lib/hw/vibrator.default.so

#lib64/drm
PRODUCT_COPY_FILES += \
    vendor/ulefone/U008_Pro/proprietary/lib64/drm/libdrmctaplugin.so:system/lib64/drm/libdrmctaplugin.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/drm/libdrmmtkplugin.so:system/lib64/drm/libdrmmtkplugin.so

#lib64/egl
PRODUCT_COPY_FILES += \
    vendor/ulefone/U008_Pro/proprietary/lib64/egl/libGLES_mali.so:system/lib64/egl/libGLES_mali.so

#lib/hw
PRODUCT_COPY_FILES += \
    vendor/ulefone/U008_Pro/proprietary/lib64/hw/audio.a2dp.default.so:system/lib64/hw/audio.a2dp.default.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/hw/audio_policy.default.so:system/lib64/hw/audio_policy.default.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/hw/audio_policy.stub.so:system/lib64/hw/audio_policy.stub.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/hw/audio.primary.default.so:system/lib64/hw/audio.primary.default.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/hw/audio.primary.mt6737m.so:system/lib64/hw/audio.primary.mt6737m.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/hw/audio.r_submix.default.so:system/lib64/hw/audio.r_submix.default.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/hw/audio.usb.default.so:system/lib64/hw/audio.usb.default.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/hw/camera.mt6737m.so:system/lib64/hw/camera.mt6737m.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/hw/gps.mt6737m.so:system/lib64/hw/gps.mt6737m.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/hw/gralloc.default.so:system/lib64/hw/gralloc.default.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/hw/gralloc.mt6737m.so:system/lib64/hw/gralloc.mt6737m.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/hw/hwcomposer.mt6737m.so:system/lib64/hw/hwcomposer.mt6737m.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/hw/keystore.default.so:system/lib64/hw/keystore.default.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/hw/lights.mt6737m.so:system/lib64/hw/lights.mt6737m.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/hw/local_time.default.so:system/lib64/hw/local_time.default.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/hw/memtrack.mt6737m.so:system/lib64/hw/memtrack.mt6737m.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/hw/power.default.so:system/lib64/hw/power.default.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/hw/sensors.mt6737m.so:system/lib64/hw/sensors.mt6737m.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/hw/vibrator.default.so:system/lib64/hw/vibrator.default.so

#lib64
PRODUCT_COPY_FILES += \
    vendor/ulefone/U008_Pro/proprietary/lib64/lib3a.so:system/lib64/lib3a.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/liba3m.so:system/lib64/liba3m.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libacdk.so:system/lib64/libacdk.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libaed.so:system/lib64/libaed.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libaudiocompensationfilter.so:system/lib64/libaudiocompensationfilter.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libaudiocomponentengine.so:system/lib64/libaudiocomponentengine.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libaudiocustparam.so:system/lib64/libaudiocustparam.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libaudiodcrflt.so:system/lib64/libaudiodcrflt.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libaudio-resampler.so:system/lib64/libaudio-resampler.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libaudiosetting.so:system/lib64/libaudiosetting.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libbessound_hd_mtk.so:system/lib64/libbessound_hd_mtk.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libblisrc32.so:system/lib64/libblisrc32.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libblisrc.so:system/lib64/libblisrc.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libbluetoothem_mtk.so:system/lib64/libbluetoothem_mtk.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libbluetooth_mtk_pure.so:system/lib64/libbluetooth_mtk_pure.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libbluetooth_mtk.so:system/lib64/libbluetooth_mtk.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libbluetooth_relayer.so:system/lib64/libbluetooth_relayer.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libBnMtkCodec.so:system/lib64/libBnMtkCodec.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libbwc.so:system/lib64/libbwc.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libcam1_utils.so:system/lib64/libcam1_utils.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libcam3_app.so:system/lib64/libcam3_app.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libcam3_hwnode.so:system/lib64/libcam3_hwnode.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libcam3_hwpipeline.so:system/lib64/libcam3_hwpipeline.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libcam3_pipeline.so:system/lib64/libcam3_pipeline.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libcam3_utils.so:system/lib64/libcam3_utils.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libcamalgo.so:system/lib64/libcamalgo.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libcam.camadapter.so:system/lib64/libcam.camadapter.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libcam.campipe.so:system/lib64/libcam.campipe.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libcam.camshot.so:system/lib64/libcam.camshot.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libcam.client.so:system/lib64/libcam.client.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libcam.device1.so:system/lib64/libcam.device1.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libcam.device3.so:system/lib64/libcam.device3.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libcamdrv_FrmB.so:system/lib64/libcamdrv_FrmB.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libcamdrv.so:system/lib64/libcamdrv.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libcameracustom.so:system/lib64/libcameracustom.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libcam.exif.so:system/lib64/libcam.exif.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libcam.exif.v3.so:system/lib64/libcam.exif.v3.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libcam.hal3a.v3.dng.so:system/lib64/libcam.hal3a.v3.dng.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libcam.hal3a.v3.so:system/lib64/libcam.hal3a.v3.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libcam.halsensor.so:system/lib64/libcam.halsensor.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libcam_hwutils.so:system/lib64/libcam_hwutils.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libcam.iopipe_FrmB.so:system/lib64/libcam.iopipe_FrmB.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libcam.iopipe.so:system/lib64/libcam.iopipe.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libcam.metadataprovider.so:system/lib64/libcam.metadataprovider.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libcam.metadata.so:system/lib64/libcam.metadata.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libcam_mmp.so:system/lib64/libcam_mmp.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libcam.paramsmgr.so:system/lib64/libcam.paramsmgr.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libcam_platform.so:system/lib64/libcam_platform.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libcam.sdkclient.so:system/lib64/libcam.sdkclient.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libcam.utils.sensorlistener.so:system/lib64/libcam.utils.sensorlistener.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libcam_utils.so:system/lib64/libcam_utils.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libcam.utils.so:system/lib64/libcam.utils.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libccci_util.so:system/lib64/libccci_util.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libcurl.so:system/lib64/libcurl.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libcustom_nvram.so:system/lib64/libcustom_nvram.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libcustom_prop.so:system/lib64/libcustom_prop.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libcvsd_mtk.so:system/lib64/libcvsd_mtk.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libdpframework.so:system/lib64/libdpframework.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libdrmmtkutil.so:system/lib64/libdrmmtkutil.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libdrmmtkwhitelist.so:system/lib64/libdrmmtkwhitelist.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libem_bt_jni.so:system/lib64/libem_bt_jni.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libem_gpio_jni.so:system/lib64/libem_gpio_jni.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libem_lte_jni.so:system/lib64/libem_lte_jni.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libem_modem_jni.so:system/lib64/libem_modem_jni.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libem_sensor_jni.so:system/lib64/libem_sensor_jni.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libem_support_jni.so:system/lib64/libem_support_jni.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libem_usb_jni.so:system/lib64/libem_usb_jni.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libem_wifi_jni.so:system/lib64/libem_wifi_jni.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libfeatureiodrv.so:system/lib64/libfeatureiodrv.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libfeatureio.so:system/lib64/libfeatureio.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libfile_op.so:system/lib64/libfile_op.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libfmcust.so:system/lib64/libfmcust.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libfs_mgr.so:system/lib64/libfs_mgr.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libgas.so:system/lib64/libgas.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libged.so:system/lib64/libged.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libgpu_aux.so:system/lib64/libgpu_aux.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libgralloc_extra.so:system/lib64/libgralloc_extra.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libgui_ext.so:system/lib64/libgui_ext.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libgybeauty420.so:system/lib64/libgybeauty420.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libgybeauty422.so:system/lib64/libgybeauty422.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libgybeauty.so:system/lib64/libgybeauty.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libh264enc_sa.ca7.so:system/lib64/libh264enc_sa.ca7.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libhdrproc.so:system/lib64/libhdrproc.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libhevce_sb.ca7.android.so:system/lib64/libhevce_sb.ca7.android.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libhwm.so:system/lib64/libhwm.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libimageio_FrmB.so:system/lib64/libimageio_FrmB.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libimageio_plat_drv_FrmB.so:system/lib64/libimageio_plat_drv_FrmB.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libimageio_plat_drv.so:system/lib64/libimageio_plat_drv.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libimageio.so:system/lib64/libimageio.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libion_mtk.so:system/lib64/libion_mtk.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libion.so:system/lib64/libion.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libJpgDecPipe.so:system/lib64/libJpgDecPipe.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libJpgEncPipe.so:system/lib64/libJpgEncPipe.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libm4u.so:system/lib64/libm4u.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libmal.so:system/lib64/libmal.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libmatv_cust.so:system/lib64/libmatv_cust.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libmdfx.so:system/lib64/libmdfx.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libmhalImageCodec.so:system/lib64/libmhalImageCodec.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libmmprofile.so:system/lib64/libmmprofile.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libmmsdkservice.feature.so:system/lib64/libmmsdkservice.feature.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libmmsdkservice.so:system/lib64/libmmsdkservice.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libmsbc_mtk.so:system/lib64/libmsbc_mtk.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libmtkcamera_client.so:system/lib64/libmtkcamera_client.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libmtkcam_fwkutils.so:system/lib64/libmtkcam_fwkutils.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libmtk_drvb.so:system/lib64/libmtk_drvb.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libmtkjpeg.so:system/lib64/libmtkjpeg.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libmtklimiter.so:system/lib64/libmtklimiter.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libmtk_mmutils.so:system/lib64/libmtk_mmutils.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libMtkOmxCore.so:system/lib64/libMtkOmxCore.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libmtkshifter.so:system/lib64/libmtkshifter.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libnvramagentclient.so:system/lib64/libnvramagentclient.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libnvram_daemon_callback.so:system/lib64/libnvram_daemon_callback.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libnvram_platform.so:system/lib64/libnvram_platform.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libnvram_sec.so:system/lib64/libnvram_sec.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libnvram.so:system/lib64/libnvram.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libperfservicenative.so:system/lib64/libperfservicenative.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libperfservice.so:system/lib64/libperfservice.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libpq_cust.so:system/lib64/libpq_cust.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libpq_prot.so:system/lib64/libpq_prot.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libpqservice.so:system/lib64/libpqservice.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/librilmtkmd2.so:system/lib64/librilmtkmd2.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/librilmtk.so:system/lib64/librilmtk.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/librrc.so:system/lib64/librrc.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libsec_mem.so:system/lib64/libsec_mem.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libspeech_enh_lib.so:system/lib64/libspeech_enh_lib.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libstagefrighthw.so:system/lib64/libstagefrighthw.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libSwJpgCodec.so:system/lib64/libSwJpgCodec.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libterservice.so:system/lib64/libterservice.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libtinyalsa.so:system/lib64/libtinyalsa.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libtinycompress.so:system/lib64/libtinycompress.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libtinyxml.so:system/lib64/libtinyxml.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libui_ext.so:system/lib64/libui_ext.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libvcodec_cap.so:system/lib64/libvcodec_cap.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libvcodecdrv.so:system/lib64/libvcodecdrv.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libvcodec_oal.so:system/lib64/libvcodec_oal.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libvcodec_utility.so:system/lib64/libvcodec_utility.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/libwebrtc_audio_preprocessing.so:system/lib64/libwebrtc_audio_preprocessing.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/mtk-rilmd2.so:system/lib64/mtk-rilmd2.so \
    vendor/ulefone/U008_Pro/proprietary/lib64/mtk-ril.so:system/lib64/mtk-ril.so

#lib64/soundfx
#PRODUCT_COPY_FILES += \
#    vendor/ulefone/U008_Pro/proprietary/lib64/soundfx/libaudiopreprocessing.so:system/lib64/soundfx/libaudiopreprocessing.so \
#    vendor/ulefone/U008_Pro/proprietary/lib64/soundfx/libbundlewrapper.so:system/lib64/soundfx/libbundlewrapper.so \
#    vendor/ulefone/U008_Pro/proprietary/lib64/soundfx/libdownmix.so:system/lib64/soundfx/libdownmix.so \
#    vendor/ulefone/U008_Pro/proprietary/lib64/soundfx/libeffectproxy.so:system/lib64/soundfx/libeffectproxy.so \
#    vendor/ulefone/U008_Pro/proprietary/lib64/soundfx/libldnhncr.so:system/lib64/soundfx/libldnhncr.so \
#    vendor/ulefone/U008_Pro/proprietary/lib64/soundfx/libreverbwrapper.so:system/lib64/soundfx/libreverbwrapper.so \
#    vendor/ulefone/U008_Pro/proprietary/lib64/soundfx/libvisualizer.so:system/lib64/soundfx/libvisualizer.so

#etc
PRODUCT_COPY_FILES += \
    vendor/ulefone/U008_Pro/proprietary/etc/agps_profiles_conf2.xml:system/etc/agps_profiles_conf2.xml \
    vendor/ulefone/U008_Pro/proprietary/etc/audio_device.xml:system/etc/audio_device.xml \
    vendor/ulefone/U008_Pro/proprietary/etc/audio_policy.conf:system/etc/audio_policy.conf \
    vendor/ulefone/U008_Pro/proprietary/etc/mtk_omx_core.cfg:system/etc/mtk_omx_core.cfg \
    vendor/ulefone/U008_Pro/proprietary/etc/perfservscntbl.txt:system/etc/perfservscntbl.txt

#etc/firmware
PRODUCT_COPY_FILES += \
    vendor/ulefone/U008_Pro/proprietary/etc/firmware/catcher_filter_1_lwg_n.bin:system/etc/firmware/catcher_filter_1_lwg_n.bin \
    vendor/ulefone/U008_Pro/proprietary/etc/firmware/dsp_1_lwg_n.bin:system/etc/firmware/dsp_1_lwg_n.bin \
    vendor/ulefone/U008_Pro/proprietary/etc/firmware/em_filter_1_lwg_n.bin:system/etc/firmware/em_filter_1_lwg_n.bin \
    vendor/ulefone/U008_Pro/proprietary/etc/firmware/modem_1_lwg_n.img:system/etc/firmware/modem_1_lwg_n.img \
    vendor/ulefone/U008_Pro/proprietary/etc/firmware/ROMv2_lm_patch_1_0_hdr.bin:system/etc/firmware/ROMv2_lm_patch_1_0_hdr.bin \
    vendor/ulefone/U008_Pro/proprietary/etc/firmware/ROMv2_lm_patch_1_1_hdr.bin:system/etc/firmware/ROMv2_lm_patch_1_1_hdr.bin \
    vendor/ulefone/U008_Pro/proprietary/etc/firmware/WIFI_RAM_CODE_6735:system/etc/firmware/WIFI_RAM_CODE_6735 \
    vendor/ulefone/U008_Pro/proprietary/etc/firmware/WMT_SOC.cfg:system/etc/firmware/WMT_SOC.cfg

#etc/firmware/mt6627
PRODUCT_COPY_FILES += \
    vendor/ulefone/U008_Pro/proprietary/etc/firmware/mt6627/mt6627_fm_v1_coeff.bin:system/etc/firmware/mt6627/mt6627_fm_v1_coeff.bin \
    vendor/ulefone/U008_Pro/proprietary/etc/firmware/mt6627/mt6627_fm_v1_patch.bin:system/etc/firmware/mt6627/mt6627_fm_v1_patch.bin \
    vendor/ulefone/U008_Pro/proprietary/etc/firmware/mt6627/mt6627_fm_v2_coeff.bin:system/etc/firmware/mt6627/mt6627_fm_v2_coeff.bin \
    vendor/ulefone/U008_Pro/proprietary/etc/firmware/mt6627/mt6627_fm_v2_patch.bin:system/etc/firmware/mt6627/mt6627_fm_v2_patch.bin \
    vendor/ulefone/U008_Pro/proprietary/etc/firmware/mt6627/mt6627_fm_v3_coeff.bin:system/etc/firmware/mt6627/mt6627_fm_v3_coeff.bin \
    vendor/ulefone/U008_Pro/proprietary/etc/firmware/mt6627/mt6627_fm_v3_patch.bin:system/etc/firmware/mt6627/mt6627_fm_v3_patch.bin \
    vendor/ulefone/U008_Pro/proprietary/etc/firmware/mt6627/mt6627_fm_v4_coeff.bin:system/etc/firmware/mt6627/mt6627_fm_v4_coeff.bin \
    vendor/ulefone/U008_Pro/proprietary/etc/firmware/mt6627/mt6627_fm_v4_patch.bin:system/etc/firmware/mt6627/mt6627_fm_v4_patch.bin \
    vendor/ulefone/U008_Pro/proprietary/etc/firmware/mt6627/mt6627_fm_v5_coeff.bin:system/etc/firmware/mt6627/mt6627_fm_v5_coeff.bin \
    vendor/ulefone/U008_Pro/proprietary/etc/firmware/mt6627/mt6627_fm_v5_patch.bin:system/etc/firmware/mt6627/mt6627_fm_v5_patch.bin

#etc/mddb
PRODUCT_COPY_FILES += \
    vendor/ulefone/U008_Pro/proprietary/etc/mddb/BPLGUInfoCustomAppSrcP_MT6735_S00_MOLY_LR9_W1444_MD_LWTG_MP_V81_6_P58_1_lwg_n:system/etc/mddb/BPLGUInfoCustomAppSrcP_MT6735_S00_MOLY_LR9_W1444_MD_LWTG_MP_V81_6_P58_1_lwg_n \
    vendor/ulefone/U008_Pro/proprietary/etc/mddb/BPMdMetaDatabase_MOLY_LR9_W1444_MD_LWTG_MP_V81_6_P58_1_lwg_n:system/etc/mddb/BPMdMetaDatabase_MOLY_LR9_W1444_MD_LWTG_MP_V81_6_P58_1_lwg_n \
    vendor/ulefone/U008_Pro/proprietary/etc/mddb/DbgInfo_LR9.W1444.MD.LWTG.MP_HCT6737M_65_M0_MOLY_LR9_W1444_MD_LWTG_MP_V81_6_P58_2017_06_30_22_12_1_lwg_n:system/etc/mddb/DbgInfo_LR9.W1444.MD.LWTG.MP_HCT6737M_65_M0_MOLY_LR9_W1444_MD_LWTG_MP_V81_6_P58_2017_06_30_22_12_1_lwg_n \
    vendor/ulefone/U008_Pro/proprietary/etc/mddb/mdm_layout_desc_1_lwg_n.dat:system/etc/mddb/mdm_layout_desc_1_lwg_n.dat

#etc/wifi
PRODUCT_COPY_FILES += \
    vendor/ulefone/U008_Pro/proprietary/etc/wifi/p2p_supplicant_overlay.conf:system/etc/wifi/p2p_supplicant_overlay.conf \
    vendor/ulefone/U008_Pro/proprietary/etc/wifi/wpa_supplicant.conf:system/etc/wifi/wpa_supplicant.conf \
    vendor/ulefone/U008_Pro/proprietary/etc/wifi/wpa_supplicant_overlay.conf:system/etc/wifi/wpa_supplicant_overlay.conf

#etc/.tp
PRODUCT_COPY_FILES += \
    vendor/ulefone/U008_Pro/proprietary/etc/.tp/thermal.conf:system/etc/.tp/thermal.conf \
    vendor/ulefone/U008_Pro/proprietary/etc/.tp/thermal.off.conf:system/etc/.tp/thermal.off.conf

#    vendor/ulefone/U008_Pro/proprietary/etc/.tp/.ht120.mtc:system/etc/.tp/.ht120.mtc \

#vendor OMX
PRODUCT_COPY_FILES += \
    vendor/ulefone/U008_Pro/proprietary/vendor/etc/mtk_omx_core.cfg:system/vendor/etc/mtk_omx_core.cfg


#vendor/lib/drm
PRODUCT_COPY_FILES += \
    vendor/ulefone/U008_Pro/proprietary/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so

#vendor/lib
PRODUCT_COPY_FILES += \
    vendor/ulefone/U008_Pro/proprietary/vendor/lib/libwvdrm_L3.so:system/vendor/lib/libwvdrm_L3.so \
    vendor/ulefone/U008_Pro/proprietary/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
    vendor/ulefone/U008_Pro/proprietary/vendor/lib/libWVStreamControlAPI_L3.so:system/vendor/lib/libWVStreamControlAPI_L3.so

#vendor/lib/mediadrm
PRODUCT_COPY_FILES += \
    vendor/ulefone/U008_Pro/proprietary/vendor/lib/mediadrm/libdrmclearkeyplugin.so:system/vendor/lib/mediadrm/libdrmclearkeyplugin.so \
    vendor/ulefone/U008_Pro/proprietary/vendor/lib/mediadrm/libmockdrmcryptoplugin.so:system/vendor/lib/mediadrm/libmockdrmcryptoplugin.so \
    vendor/ulefone/U008_Pro/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so


#vendor/lib64/mediadrm
PRODUCT_COPY_FILES += \
    vendor/ulefone/U008_Pro/proprietary/vendor/lib64/mediadrm/libdrmclearkeyplugin.so:system/vendor/lib64/mediadrm/libdrmclearkeyplugin.so \
    vendor/ulefone/U008_Pro/proprietary/vendor/lib64/mediadrm/libmockdrmcryptoplugin.so:system/vendor/lib64/mediadrm/libmockdrmcryptoplugin.so

#vendor/media
PRODUCT_COPY_FILES += \
    vendor/ulefone/U008_Pro/proprietary/vendor/media/LMspeed_508.emd:system/vendor/media/LMspeed_508.emd \
    vendor/ulefone/U008_Pro/proprietary/vendor/media/PFFprec_600.emd:system/vendor/media/PFFprec_600.emd

#usr/keylayout
PRODUCT_COPY_FILES += \
    vendor/ulefone/U008_Pro/proprietary/usr/keylayout/ACCDET.kl:usr/keylayout/ACCDET.kl \
    vendor/ulefone/U008_Pro/proprietary/usr/keylayout/AVRCP.kl:usr/keylayout/AVRCP.kl \
    vendor/ulefone/U008_Pro/proprietary/usr/keylayout/Generic.kl:usr/keylayout/Generic.kl \
    vendor/ulefone/U008_Pro/proprietary/usr/keylayout/gpio-keys.kl:usr/keylayout/gpio-keys.kl \
    vendor/ulefone/U008_Pro/proprietary/usr/keylayout/mtk-kpd.kl:usr/keylayout/mtk-kpd.kl \
    vendor/ulefone/U008_Pro/proprietary/usr/keylayout/mtk-tpd.kl:usr/keylayout/mtk-tpd.kl \
    vendor/ulefone/U008_Pro/proprietary/usr/keylayout/mtk-tpd-kpd.kl:usr/keylayout/mtk-tpd-kpd.kl


